FROM node:20-alpine
WORKDIR /src
RUN npm install -g pm2
COPY package*.json ./
ARG NODE_ENV
RUN if [ "$NODE_ENV" = "production" ]; then \
    npm install --only=production; \
    else npm install; \
    fi   
COPY . .
EXPOSE 3000
RUN chmod +x entrypoint.sh
ENTRYPOINT ["sh", "./entrypoint.sh"]
CMD ["pm2"]

